// src/components/Footer.jsx
function Footer() {
  return (
    <footer className="footer">
      <div className="container footer-inner">
        <div className="footer-brand">
          <p className="footer-kicker">PUSAN NATIONAL UNIVERSITY PAN FLUTE CLUB</p>
          <p className="footer-title">PINOCCHIO ARCHIVE</p>
          <p className="footer-description">
            공연 기록, 연습 자료, 동아리 일정을 차곡차곡 모아두는 피노키오의 디지털 아카이브
          </p>
        </div>

        <div className="footer-copy">
          <p>© 2026 PINOCCHIO. All rights reserved.</p>
          <p>부산대학교 팬플룻 동아리 피노키오</p>
        </div>
      </div>
    </footer>
  );
}

export default Footer;

// src/lib/components/Footer.svelte
<footer class="footer">
  <div class="container footer-inner">
    <div class="footer-brand">
      <p class="footer-kicker">PUSAN NATIONAL UNIVERSITY PAN FLUTE CLUB</p>
      <p class="footer-title">PINOCCHIO ARCHIVE</p>
      <p class="footer-description">
        공연 기록, 연습 자료, 동아리 일정을 차곡차곡 모아두는 피노키오의 디지털 아카이브
      </p>
    </div>

    <div class="footer-copy">
      <p>© 2026 PINOCCHIO. All rights reserved.</p>
      <p>부산대학교 팬플룻 동아리 피노키오</p>
    </div>
  </div>
</footer>
