// src/components/Header.jsx
import { Link } from "react-router-dom";
import { useState } from "react";
import { PromptDialog } from "./Dialog";

function Header({ isAdmin, isConfigured, isLoading, isSubmitting, onLogin, onLogout }) {
  const [status, setStatus] = useState(null);
  const [isLoginDialogOpen, setIsLoginDialogOpen] = useState(false);
  const [adminCode, setAdminCode] = useState("");
  const [adminCodeError, setAdminCodeError] = useState("");

  const handleAdminAction = async () => {
    setStatus(null);

    if (isAdmin) {
      try {
        await onLogout();
        setStatus(null);
      } catch (error) {
        setStatus({
          type: "error",
          text: error instanceof Error ? error.message : "로그아웃에 실패했습니다.",
        });
      }

      return;
    }

    if (!isConfigured) {
      setStatus({
        type: "error",
        text: "관리자 로그인이 아직 설정되지 않았습니다. ADMIN_CODE 또는 ADMIN_SESSION_SECRET을 확인해 주세요.",
      });
      return;
    }

    setAdminCode("");
    setAdminCodeError("");
    setIsLoginDialogOpen(true);
  };

  const handleLoginConfirm = async () => {
    if (!adminCode.trim()) {
      setAdminCodeError("관리자 코드를 입력해주세요.");
      return;
    }

    try {
      await onLogin(adminCode.trim());
      setIsLoginDialogOpen(false);
      setAdminCode("");
      setAdminCodeError("");
      setStatus(null);
    } catch (error) {
      setAdminCodeError(
        error instanceof Error ? error.message : "관리자 로그인에 실패했습니다."
      );
    }
  };

  return (
    <header className="header">
      <div className="container header-inner">
        <Link to="/" className="brand-lockup" aria-label="PINOCCHIO 홈으로 이동">
          <span className="logo-caption">PUSAN NATIONAL UNIVERSITY</span>
          <span className="logo">PINOCCHIO</span>
          <span className="brand-subtitle">PAN FLUTE CLUB ARCHIVE</span>
        </Link>

        <nav className="nav" aria-label="주요 메뉴">
          <Link to="/">홈</Link>
          <Link to="/about">동아리 소개</Link>
          <Link to="/scores">악보실</Link>
          <Link to="/videos">공연 영상</Link>
          <Link to="/schedule">일정</Link>
          <span className="nav-admin-group">
            <Link to="/guestbook">방명록</Link>
            <button
              type="button"
              className={`nav-admin-button${isAdmin ? " is-active" : ""}`}
              onClick={handleAdminAction}
              disabled={isLoading || isSubmitting}
            >
              {isLoading ? "확인 중" : isSubmitting ? "처리 중" : isAdmin ? "로그아웃" : "관리자"}
            </button>
          </span>
        </nav>
      </div>
      {status ? (
        <div className="container">
          <p className={`guestbook-status header-status is-${status.type}`}>{status.text}</p>
        </div>
      ) : null}
      <PromptDialog
        open={isLoginDialogOpen}
        title="관리자 로그인"
        message="관리자 코드를 입력하면 관리 모드로 전환됩니다."
        value={adminCode}
        placeholder="관리자 코드"
        errorText={adminCodeError}
        confirmLabel="로그인"
        isSubmitting={isSubmitting}
        onChange={(value) => {
          setAdminCode(value);
          if (adminCodeError) {
            setAdminCodeError("");
          }
        }}
        onConfirm={handleLoginConfirm}
        onClose={() => {
          if (!isSubmitting) {
            setIsLoginDialogOpen(false);
            setAdminCode("");
            setAdminCodeError("");
          }
        }}
      />
    </header>
  );
}

export default Header;

// src/lib/components/Header.svelte
<script>
  import PromptDialog from "$lib/components/PromptDialog.svelte";

  let {
    isAdmin,
    isConfigured,
    isLoading,
    isSubmitting,
    onLogin,
    onLogout,
  } = $props();

  let status = $state(null);
  let isLoginDialogOpen = $state(false);
  let adminCode = $state("");
  let adminCodeError = $state("");

  const adminButtonLabel = $derived(
    isLoading ? "확인 중" : isSubmitting ? "처리 중" : isAdmin ? "로그아웃" : "관리자"
  );

  async function handleAdminAction() {
    status = null;

    if (isAdmin) {
      try {
        await onLogout();
        status = null;
      } catch (error) {
        status = {
          type: "error",
          text: error instanceof Error ? error.message : "로그아웃에 실패했습니다.",
        };
      }

      return;
    }

    if (!isConfigured) {
      status = {
        type: "error",
        text: "관리자 로그인이 아직 설정되지 않았습니다. ADMIN_CODE 또는 ADMIN_SESSION_SECRET을 확인해 주세요.",
      };
      return;
    }

    adminCode = "";
    adminCodeError = "";
    isLoginDialogOpen = true;
  }

  async function handleLoginConfirm() {
    if (!adminCode.trim()) {
      adminCodeError = "관리자 코드를 입력해주세요.";
      return;
    }

    try {
      await onLogin(adminCode.trim());
      isLoginDialogOpen = false;
      adminCode = "";
      adminCodeError = "";
      status = null;
    } catch (error) {
      adminCodeError =
        error instanceof Error ? error.message : "관리자 로그인에 실패했습니다.";
    }
  }

  function handleDialogClose() {
    if (isSubmitting) {
      return;
    }

    isLoginDialogOpen = false;
    adminCode = "";
    adminCodeError = "";
  }
</script>

<header class="header">
  <div class="container header-inner">
    <a href="/" class="brand-lockup" aria-label="PINOCCHIO 홈으로 이동">
      <span class="logo-caption">PUSAN NATIONAL UNIVERSITY</span>
      <span class="logo">PINOCCHIO</span>
      <span class="brand-subtitle">PAN FLUTE CLUB ARCHIVE</span>
    </a>

    <nav class="nav" aria-label="주요 메뉴">
      <a href="/">홈</a>
      <a href="/about">동아리 소개</a>
      <a href="/scores">악보실</a>
      <a href="/videos">공연 영상</a>
      <a href="/schedule">일정</a>
      <span class="nav-admin-group">
        <a href="/guestbook">방명록</a>
        <button
          type="button"
          class={`nav-admin-button${isAdmin ? " is-active" : ""}`}
          onclick={handleAdminAction}
          disabled={isLoading || isSubmitting}
        >
          {adminButtonLabel}
        </button>
      </span>
    </nav>
  </div>

  {#if status}
    <div class="container">
      <p class={`guestbook-status header-status is-${status.type}`}>{status.text}</p>
    </div>
  {/if}

  <PromptDialog
    open={isLoginDialogOpen}
    title="관리자 로그인"
    message="관리자 코드를 입력하면 관리 모드로 전환됩니다."
    value={adminCode}
    placeholder="관리자 코드"
    errorText={adminCodeError}
    confirmLabel="로그인"
    {isSubmitting}
    onChange={(value) => {
      adminCode = value;

      if (adminCodeError) {
        adminCodeError = "";
      }
    }}
    onConfirm={handleLoginConfirm}
    onClose={handleDialogClose}
  />
</header>
